document.write('<div id="menu">');
document.write('<ul>');
document.write('<li class="current_page_item"><span><a href="#">Home</a></span></li>');
document.write('<li><a href="#">Blog</a></li>');
document.write('<li><a href="#">Photos</a></li>');
document.write('<li><a href="#">About</a></li>');
document.write('<li><a href="#">Links</a></li>');
document.write('<li><a href="#">Contact</a></li>');
document.write('</ul>');
document.write('</div>');
document.write('<!-- end #menu -->');
document.write('<div id="header">');
document.write('<div id="logo">');
document.write('<h1><a href="#">Rain on Leaves</a></h1>');
document.write('<p>Template Design by CSS Template</p>');
document.write('</div>');
document.write('</div>');
document.write('<!-- end #header -->');
